---
permalink: online-help/concept-configuring-the-destination-and-schedule-for-database-dump-backups.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez configurer les paramètres de sauvegarde de la base de données Unified Manager pour définir le chemin de sauvegarde de la base de données, le nombre de rétention et les planifications de sauvegarde. Vous pouvez activer des sauvegardes planifiées quotidiennement ou hebdomadaires. Par défaut, les sauvegardes planifiées sont désactivées. 
---
= Configuration des paramètres de sauvegarde de la base de données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer les paramètres de sauvegarde de la base de données Unified Manager pour définir le chemin de sauvegarde de la base de données, le nombre de rétention et les planifications de sauvegarde. Vous pouvez activer des sauvegardes planifiées quotidiennement ou hebdomadaires. Par défaut, les sauvegardes planifiées sont désactivées.



== Avant de commencer

* Vous devez avoir le rôle opérateur, administrateur d'applications ou administrateur de stockage.
* Vous devez disposer d'au moins 150 Go d'espace disponible dans l'emplacement que vous définissez comme chemin de sauvegarde.
+
Il est recommandé d'utiliser un emplacement distant externe au système hôte Unified Manager.

* Lorsque Unified Manager est installé sur un système Linux, vérifiez que l'utilisateur « jboss » dispose des autorisations d'écriture sur le répertoire de sauvegarde.
* Vous ne devez pas planifier d'opérations de sauvegarde immédiatement après l'ajout d'un nouveau cluster alors que Unified Manager collecte 15 jours de données historiques de performance.




== Description de la tâche

La première sauvegarde est effectuée moins de temps que les sauvegardes suivantes, car la première sauvegarde est une sauvegarde complète. Une sauvegarde complète peut dépasser 1 Go et peut prendre entre trois et quatre heures. Les sauvegardes suivantes sont incrémentielles et requièrent moins de temps.

[NOTE]
====
Si vous constatez que le nombre de fichiers de sauvegarde incrémentielle est trop important pour l'espace alloué aux sauvegardes, reportez-vous à la section https://kb.netapp.com/app/answers/answer_view/a_id/1087704/loc/en_US["Réponse de la base de connaissances 1087704"] pour savoir comment vous pouvez créer une nouvelle sauvegarde complète régulièrement pour remplacer l'ancienne sauvegarde complète et tous ses fichiers incrémentiels enfant.

====


== Étapes

. Dans le volet de navigation de gauche, cliquez sur *général* > *sauvegarde de base de données*.
. Dans la page *sauvegarde de base de données*, cliquez sur *Paramètres de sauvegarde*.
. Configurez les valeurs appropriées pour un chemin de sauvegarde, le nombre de rétention et la planification.
+
La valeur par défaut pour le nombre de rétention est 10 ; vous pouvez utiliser 0 pour créer des sauvegardes illimitées.

. Sélectionnez le bouton *planifié quotidien* ou *planifié hebdomadaire*, puis spécifiez les détails de l'horaire.
. Cliquez sur *appliquer*.

