---
permalink: online-help/concept-managing-feature-settings.html 
sidebar: sidebar 
keywords: uploading scripts,API gateway,SLO or policy-based storage management,timeout,Active IQ platform events 
summary: 'La page Paramètres des fonctionnalités vous permet d"activer et de désactiver des fonctionnalités spécifiques dans Active IQ Unified Manager, telles que la création et la gestion d"objets de stockage basés sur des stratégies, l"activation de la passerelle d"API, le téléchargement de scripts pour la gestion des alertes, la temporisation d"une session en cas d"inactivité pendant une période donnée, Et désactiver la réception des événements relatifs à la plateforme Active IQ.' 
---
= Gestion des paramètres des fonctions
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La page Paramètres des fonctionnalités vous permet d'activer et de désactiver des fonctionnalités spécifiques dans Active IQ Unified Manager, telles que la création et la gestion d'objets de stockage basés sur des stratégies, l'activation de la passerelle d'API, le téléchargement de scripts pour la gestion des alertes, la temporisation d'une session en cas d'inactivité pendant une période donnée, Et désactiver la réception des événements relatifs à la plateforme Active IQ.

[NOTE]
====
La page Paramètres de la fonction n'est disponible que pour les utilisateurs ayant le rôle d'administrateur d'application.

====
Pour plus d'informations sur le téléchargement de scripts, consultez la section « activation et désactivation de la capacité de téléchargement de scripts ».

Activation et désactivation de la capacité à télécharger des scripts
