---
permalink: online-help/concept-all-workloads.html 
sidebar: sidebar 
keywords: workloads,workloads 
summary: La vue toutes les charges de travail affiche la liste de toutes les charges de travail disponibles sur les clusters du data Center. 
---
= Toutes les charges de travail
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vue toutes les charges de travail affiche la liste de toutes les charges de travail disponibles sur les clusters du data Center.

La vue toutes les charges de travail répertorie les charges de travail de stockage associées aux clusters ONTAP gérés par Unified Manager. La page vous permet également d'attribuer des règles d'efficacité du stockage et des niveaux de services de performances aux charges de travail de stockage.

Lorsque vous ajoutez des clusters à Unified Manager, les charges de travail de stockage de chaque cluster sont automatiquement découvertes et affichées sur cette page, à l'exception des volumes FlexGroup et de leurs composants.

Unified Manager commence à analyser les charges de travail à des fins de recommandation (niveaux de service de performances recommandés) uniquement après le démarrage des opérations d'E/S sur les charges de travail de stockage. Concernant les charges de travail de stockage récemment découvertes sur lesquelles il n'y a pas d'opérations d'E/S, l'état est « en attente d'E/S ». Une fois les opérations d'E/S traitées sur les charges de travail de stockage, Unified Manager commence l'analyse et l'état des charges de travail devient « apprentissage... ». Une fois l'analyse terminée (dans les 24 heures qui suivent le début des opérations d'E/S), les niveaux de service de performances recommandés sont affichés pour les charges de travail du stockage.

Avec l'option *workloads* > *toutes les charges de travail*, vous pouvez effectuer plusieurs tâches :

* Ajout ou provisionnement de workloads de stockage
* Afficher et filtrer la liste des charges de travail
* Attribuez des niveaux de services de performances à des charges de travail de stockage individuelles
* Attribuez des niveaux de service de performances recommandés par le système à toutes les charges de travail non affectées
* Définissez des règles d'efficacité du stockage à des charges de travail de stockage




== Ajout ou provisionnement de charges de travail de stockage

Vous pouvez ajouter ou provisionner les charges de travail de stockage aux LUN prises en charge (prise en charge des protocoles iSCSI et FCP), aux partages de fichiers NFS et aux partages SMB.



== Afficher et filtrer les workloads

Sur l'écran toutes les charges de travail, vous pouvez afficher toutes les charges de travail de votre data Center ou rechercher des charges de travail de stockage spécifiques en fonction des niveaux de services de performance qui leur sont affectés ou des noms de charge de travail. Vous pouvez utiliser l'icône de filtre pour entrer des conditions spécifiques à votre recherche. Vous pouvez effectuer une recherche selon différentes conditions de filtre, par exemple par le cluster hôte ou la machine virtuelle de stockage. Si vous sélectionnez l'option *Total de la capacité*, vous pouvez effectuer une recherche en fonction de la capacité totale des charges de travail. Le nombre de charges de travail renvoyées peut varier en fonction de la condition de filtre exacte saisie, car la capacité est comparée à un niveau d'octet. Les informations de stockage des charges de travail s'affichent à l'écran, telles que le cluster hôte et la machine virtuelle de stockage, ainsi que la règle d'efficacité du stockage et de niveau de service de performances, le cas échéant.

Cette page vous permet également d'afficher les performances détaillées d'une charge de travail. Vous pouvez afficher des informations détaillées sur les IOPS, la capacité et la latence de la charge de travail en cliquant sur le bouton *choisir / Commander les colonnes* et en sélectionnant des colonnes spécifiques à afficher. La colonne vue des performances affiche les IOPS moyennes et maximales d'une charge de travail. Vous pouvez cliquer sur l'icône de l'analyseur de workloads pour afficher l'analyse détaillée des IOPS. Le bouton *Analyze Workload* de la fenêtre contextuelle analyse d'IOPS vous permet d'accéder à la page analyse de charge de travail, où vous pouvez sélectionner une plage de temps et afficher les tendances de latence, de débit et de capacité de la charge de travail sélectionnée. Pour plus d'informations sur l'analyseur de charge de travail, reportez-vous à la section _Dépannage des charges de travail à l'aide de l'analyseur de charge de travail_

link:concept-troubleshooting-workloads-using-the-workload-analyzer.html["Dépannage des charges de travail à l'aide de l'analyseur de workloads"]



== Assignation de niveaux de services de performances aux charges de travail de stockage

Vous pouvez attribuer un niveau de services hautes performances à une ou plusieurs charges de travail de stockage. En utilisant les différentes navigations à l'écran, vous pouvez attribuer un niveau de service de performances spécifique ou recommandé par le système aux charges de travail.



== Attribuer des niveaux de service de performances recommandés par le système à toutes les charges de travail non affectées

Vous pouvez attribuer des niveaux de service de performances à toutes les charges de travail de stockage d'un data Center n'ayant pas de PSLs attribués. En effet, des niveaux de service de performances recommandés par le système sont disponibles pour les charges de travail. Cette fonctionnalité est particulièrement efficace pour les charges de travail qui ne disposent d'aucun niveau de service de performances recommandé par le système. Pour utiliser cette fonctionnalité, cliquez sur le bouton *affecter les PSLs* recommandés par le système. Le système évalue en interne les niveaux de service de performances appropriés pour les charges de travail de stockage non affectées et affiche le nombre total de charges de travail sur lesquelles les niveaux de service de performance peuvent être affectés.



== Assignation de règles Storage Efficiency aux charges de travail de stockage

Vous pouvez affecter une règle d'efficacité du stockage à une ou plusieurs charges de travail de stockage. Si vous utilisez les différentes navigations affichées à l'écran, vous pouvez attribuer une politique d'efficacité du stockage spécifique aux charges de travail du stockage.



== Assignation conjointe de niveaux de service en matière de performances et de règles d'efficacité du stockage

Vous pouvez attribuer un niveau de service en matière de performances et une règle d'efficacité du stockage à une seule charge de travail à la fois. Voici la procédure à suivre :

. Cliquez sur l'icône d'édition de la ligne, puis sur *Modifier*.
+
Les champs *niveau de service de performances attribué* et *Stratégie d'efficacité du stockage* sont activés.

. Sélectionnez la règle de niveau de service performances et d'efficacité du stockage requise.
. Cliquez sur l'icône de vérification pour appliquer les modifications.




== L'analyse des critères de performances et de capacité d'une charge de travail

Vous pouvez afficher les informations de performances d'une charge de travail pour faciliter le dépannage en cliquant sur l'icône du graphique à barres dans la colonne *Affichage des performances*. Pour afficher les graphiques de performances et de capacité sur la page analyse de la charge de travail pour analyser l'objet, cliquez sur le bouton *analyser la charge de travail*.
