---
permalink: online-help/reference-backup-settings-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez utiliser la boîte de dialogue Paramètres de sauvegarde pour spécifier un chemin de sauvegarde et un nombre de rétention, et pour activer un programme de sauvegarde pour une instance Unified Manager sélectionnée. 
---
= Boîte de dialogue Paramètres de sauvegarde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la boîte de dialogue Paramètres de sauvegarde pour spécifier un chemin de sauvegarde et un nombre de rétention, et pour activer un programme de sauvegarde pour une instance Unified Manager sélectionnée.

Vous pouvez modifier les paramètres de sauvegarde suivants de la base de données :

* *Chemin*
+
Indique le chemin d'accès à l'emplacement où vous stockez les fichiers de sauvegarde. Le tableau suivant indique le format du chemin de sauvegarde et les emplacements par défaut pour différents systèmes d'exploitation :

+
[cols="1a,1a"]
|===
| Système d'exploitation hôte | Format du chemin de sauvegarde 


 a| 
Appliance virtuelle
 a| 
`/opt/netapp/data/ocum-backup`



 a| 
Red Hat Enterprise Linux ou CentOS
 a| 
`/data/ocum-backup`



 a| 
Microsoft Windows
 a| 
`C:\ProgramData\NetApp\OnCommandAppData\ocum\backup\`

|===
* *Nombre de rétention*
+
Spécifie le nombre maximal de sauvegardes à conserver par Unified Manager. La valeur par défaut est dix.

* *Quotidien planifié*
+
Spécifie le planning de sauvegarde quotidien avec l'heure.

* *Hebdomadaire planifié*
+
Spécifie le programme de sauvegarde hebdomadaire avec le jour et l'heure.

* *Aucun*
+
Spécifie qu'aucune sauvegarde ne sera créée.





== Boutons de commande

* *Appliquer*
+
Enregistre le fichier de sauvegarde et ferme la boîte de dialogue. Unified Manager enregistre le fichier de sauvegarde au format suivant : `um_um_version_backup_os_timestamp.7z`.


