---
permalink: online-help/reference-logical-interface-events.html 
sidebar: sidebar 
keywords:  
summary: 'Les événements LIF fournissent des informations sur l"état de vos LIF, qui vous permettent de contrôler en cas de problèmes potentiels. Les événements sont regroupés par zone d"impact et incluent le nom de l"événement et de l"interruption, le niveau d"impact, le type de source et la gravité.' 
---
= Événements d'interface logique (LIF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les événements LIF fournissent des informations sur l'état de vos LIF, qui vous permettent de contrôler en cas de problèmes potentiels. Les événements sont regroupés par zone d'impact et incluent le nom de l'événement et de l'interruption, le niveau d'impact, le type de source et la gravité.



== Domaine d'impact : disponibilité

[cols="1a,1a,1a,1a"]
|===
| Nom de l'événement(Nom du piège) | Niveau d'impact | Type de source | Gravité 


 a| 
LIF Status down (ocumEvtLifStatusDown)
 a| 
Risques
 a| 
Interface
 a| 
Erreur



 a| 
Basculement LIF impossible(ocumEvtLiftFailoverNotable)
 a| 
Risques
 a| 
Interface
 a| 
Avertissement



 a| 
LIF not at Home Port (ocumEvtLiftLiftAtHomePort)
 a| 
Risques
 a| 
Interface
 a| 
Avertissement

|===


== Zone d'impact : configuration

[cols="1a,1a,1a,1a"]
|===
| Nom de l'événement(Nom du piège) | Niveau d'impact | Type de source | Gravité 


 a| 
Route LIF non configurée (non applicable)
 a| 
Événement
 a| 
Interface
 a| 
Informations

|===


== Zone d'impact : performances

[cols="1a,1a,1a,1a"]
|===
| Nom de l'événement(Nom du piège) | Niveau d'impact | Type de source | Gravité 


 a| 
Seuil critique de l'interface réseau MB/s (ocumNetworkLifMbpsincident)
 a| 
Gestion des
 a| 
Interface
 a| 
Primordial



 a| 
Seuil d'avertissement de l'interface réseau MB/s dépassé(ocumNetworkLifMbpsWarning)
 a| 
Risques
 a| 
Interface
 a| 
Avertissement



 a| 
Violation du seuil critique de l'interface FCP MB/s (ocumFcpLifMbpsincident)
 a| 
Gestion des
 a| 
Interface
 a| 
Primordial



 a| 
Seuil d'avertissement de l'interface FCP MB/s dépassé(ocumFcpLifMbpsWarning)
 a| 
Risques
 a| 
Interface
 a| 
Avertissement



 a| 
Interface NVMf FCP MB/s Critical Threshold brèche (ocumNvmfFcLifMbpsincident)
 a| 
Gestion des
 a| 
Interface
 a| 
Primordial



 a| 
Interface NVMf FCP MB/s seuil d'avertissement dépassé(ocumNvmfFcLifMbpsWarning)
 a| 
Risques
 a| 
Interface
 a| 
Avertissement

|===