---
permalink: reporting/concept-understanding-reports.html 
sidebar: sidebar 
keywords:  
summary: 'Des rapports affichent des informations détaillées sur le stockage, le réseau, la qualité de service et les relations de protection, vous permettant d"identifier et de résoudre les problèmes potentiels avant qu"ils ne se produisent.' 
---
= Présentation des rapports
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Des rapports affichent des informations détaillées sur le stockage, le réseau, la qualité de service et les relations de protection, vous permettant d'identifier et de résoudre les problèmes potentiels avant qu'ils ne se produisent.

Vous pouvez télécharger des rapports au format PDF ou CSV. Lorsque vous personnalisez une vue, vous pouvez l'enregistrer avec un nom unique pour une utilisation ultérieure. Vous pouvez également planifier un rapport basé sur cette vue pour qu'il s'exécute régulièrement et le partager avec d'autres.

Vous pouvez gérer tous les rapports qui ont été planifiés à partir de la page programmes de rapports.

[NOTE]
====
Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage pour gérer les rapports.

====