---
permalink: reporting/concept-scheduling-reports.html 
sidebar: sidebar 
keywords:  
summary: 'Après avoir une vue que vous souhaitez réutiliser et partager comme rapport, vous pouvez la planifier à l"aide de Active IQ Unified Manager. Vous pouvez gérer les rapports programmés, modifier les destinataires et la fréquence de distribution de chaque planning de rapport.' 
---
= Planification des rapports
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir une vue que vous souhaitez réutiliser et partager comme rapport, vous pouvez la planifier à l'aide de Active IQ Unified Manager. Vous pouvez gérer les rapports programmés, modifier les destinataires et la fréquence de distribution de chaque planning de rapport.

Vous pouvez planifier la plupart des vues ou des pages d'inventaire dans Unified Manager. Les exceptions sont les événements, qui sont des rapports que vous pouvez télécharger sous forme de fichiers CSV, mais vous ne pouvez pas planifier d'événements pour la régénération et le partage. Vous ne pouvez pas non plus télécharger ni planifier les tableaux de bord, les favoris ou les pages de configuration.

Vous pouvez programmer les vues intégrées ou les vues que vous personnalisez. Vous pouvez choisir le type de fichier à envoyer, CSV ou PDF. Lorsque vous planifiez un rapport pour la première fois, vous pouvez le télécharger et vous attribuer en tant que seul destinataire à voir le rapport, car vos destinataires le verront.
