---
permalink: reporting/reference-types-of-reports.html 
sidebar: sidebar 
keywords:  
summary: 'Liste complète des vues et pages d"inventaire disponibles sous forme de rapports que vous pouvez personnaliser, enregistrer, télécharger et planifier.' 
---
= Types de rapports
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Liste complète des vues et pages d'inventaire disponibles sous forme de rapports que vous pouvez personnaliser, enregistrer, télécharger et planifier.



== Rapports Active IQ Unified Manager

|===
| Type | Objet réseau ou de stockage 


 a| 
Puissance
 a| 
Clusters

64 bits

Volumes

Qtrees



 a| 
Santé
 a| 
Clusters

Nœuds

64 bits

Machines virtuelles de stockage

Volumes

Partages SMB/CIFS

Partages NFS



 a| 
Performance
 a| 
Clusters

Nœuds

64 bits

Machines virtuelles de stockage

Volumes

LUN

Espaces de noms NVMe

Interfaces réseau (LIFS)

Ports



 a| 
Qualité de service
 a| 
Groupes de règles de QoS classiques

Groupes de règles de QoS adaptative

Groupes de règles de l'objectif de niveau de service de performances



 a| 
Relations de protection des volumes (disponibles à partir de la page volumes)
 a| 
Toutes les relations

État du transfert du dernier mois

Taux de transfert du dernier mois

|===