---
permalink: install-windows/task-upgrading-mysql-on-windows-ocum.html 
sidebar: sidebar 
keywords: Active IQ Unified Manager 
summary: 'Sur le serveur Windows sur lequel Unified Manager est installé, vous pouvez mettre à niveau MySQL vers une version supérieure afin d"obtenir des correctifs pour les vulnérabilités de sécurité. Pour toute mise à niveau mineure, la version de base de MySQL doit être 8.0.17 ou ultérieure. Si la version installée de MySQL sur votre système est antérieure à 8.0.17, le processus de mise à niveau de Unified Manager 9.7 met automatiquement à niveau MySQL vers 8.0.17. Vous ne devez pas exécuter une mise à niveau autonome de MySQL d"une version antérieure à 8.0.17.' 
---
= Mise à niveau de MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sur le serveur Windows sur lequel Unified Manager est installé, vous pouvez mettre à niveau MySQL vers une version supérieure afin d'obtenir des correctifs pour les vulnérabilités de sécurité. Pour toute mise à niveau mineure, la version de base de MySQL doit être 8.0.17 ou ultérieure. Si la version installée de MySQL sur votre système est antérieure à 8.0.17, le processus de mise à niveau de Unified Manager 9.7 met automatiquement à niveau MySQL vers 8.0.17. Vous ne devez pas exécuter une mise à niveau autonome de MySQL d'une version antérieure à 8.0.17.



== Avant de commencer

[NOTE]
====
Si la version installée de MySQL sur votre système est 5.7, alors vous ne devez pas essayer de mettre directement à niveau MySQL vers la version 8.0.17. Cela entraîne la perte des données d'application.

====
* Vous devez disposer des privilèges d'administrateur Windows pour le système sur lequel Unified Manager est installé.
* Vous devez avoir le mot de passe pour l'utilisateur root MySQL.




== Étapes

. Connectez-vous en tant qu'utilisateur administrateur sur la machine hôte Unified Manager.
. Télécharger la version appropriée de MySQL sur le système cible.
. Utilisez la console des services Windows pour arrêter les services Unified Manager suivants :
+
** Service d'acquisition NetApp Active IQ (Ocie-au)
** Service de serveur de gestion NetApp Active IQ (Oncommandsvc)
** MYSQL8


. Cliquez sur le bouton `.msi` Paquet pour appeler la mise à niveau de MySQL et suivre les instructions à l'écran pour terminer la mise à niveau.
. Démarrez les services Unified Manager à l'aide de la console des services Windows :
+
** MYSQL8
** Service de serveur de gestion NetApp Active IQ (Oncommandsvc)
** Service d'acquisition NetApp Active IQ (Ocie-au)



