---
permalink: install-windows/task-changing-the-jboss-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez créer un nouveau mot de passe JBoss personnalisé pour remplacer le mot de passe par défaut défini lors de l"installation. Cette tâche est facultative, mais certains sites peuvent nécessiter cette fonctionnalité de sécurité pour remplacer le paramètre par défaut d"installation d"Unified Manager. Cette opération modifie également le mot de passe que JBoss utilise pour accéder à MySQL.' 
---
= Modification du mot de passe JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un nouveau mot de passe JBoss personnalisé pour remplacer le mot de passe par défaut défini lors de l'installation. Cette tâche est facultative, mais certains sites peuvent nécessiter cette fonctionnalité de sécurité pour remplacer le paramètre par défaut d'installation d'Unified Manager. Cette opération modifie également le mot de passe que JBoss utilise pour accéder à MySQL.



== Avant de commencer

* Vous devez disposer des privilèges d'administrateur Windows pour le système sur lequel Unified Manager est installé.
* Vous devez avoir le mot de passe pour l'utilisateur root MySQL.
* Pour accéder à ces informations, vous devez pouvoir `password.bat` script dans le répertoire `\Program Files\NetApp\essentials\bin`.




== Étapes

. Connectez-vous en tant qu'utilisateur administrateur sur la machine hôte Unified Manager.
. Utilisez la console des services Windows pour arrêter les services Unified Manager suivants :
+
** Service d'acquisition NetApp Active IQ (Ocie-au)
** Service de serveur de gestion NetApp Active IQ (Oncommandsvc)


. Lancez le `password.bat` script pour lancer le processus de modification du mot de passe : `C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`
. Lorsque vous y êtes invité, saisissez le mot de passe utilisateur root MySQL.
. Lorsque vous y êtes invité, entrez le mot de passe utilisateur JBoss actuel.
+
Le mot de passe par défaut est `D11h1aMu@79%`.

. Lorsque vous y êtes invité, saisissez le nouveau mot de passe utilisateur JBoss, puis saisissez-le à nouveau pour confirmation.
+
Les messages de confirmation s'affichent lorsque les modifications sont effectuées, puis vous êtes invité une dernière fois au nouveau mot de passe utilisateur JBoss.

. Saisissez encore une fois le nouveau mot de passe utilisateur JBoss.
. Une fois le script terminé, démarrez les services Unified Manager à l'aide de la console des services Windows :
+
** Service de serveur de gestion NetApp Active IQ (Oncommandsvc)
** Service d'acquisition NetApp Active IQ (Ocie-au)


. Une fois tous les services démarrés, vous pouvez vous connecter à l'interface utilisateur de Unified Manager.

