---
permalink: install-linux/task-manually-configuring-the-mysql-repository.html 
sidebar: sidebar 
keywords: Data Center Manager 
summary: 'Si le système sur lequel vous installez Unified Manager n"a pas accès au référentiel MySQL Community Edition, vous devez télécharger et configurer manuellement le référentiel pour une installation réussie.' 
---
= Configuration manuelle du référentiel MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si le système sur lequel vous installez Unified Manager n'a pas accès au référentiel MySQL Community Edition, vous devez télécharger et configurer manuellement le référentiel pour une installation réussie.



== Description de la tâche

Le référentiel MySQL permet d'accéder au logiciel MySQL requis qui doit être installé sur votre système.

[NOTE]
====
Cette tâche peut échouer si le système n'a pas de connexion Internet. Reportez-vous à la documentation MySQL si le système sur lequel vous installez Unified Manager ne dispose pas d'un accès Internet.

====


== Étapes

. Téléchargez le référentiel MySQL approprié pour votre installation : `+wget http://repo.mysql.com/yum/mysql-8.0-community/el/7/x86_64/mysql80-community-release-el7-3.noarch.rpm+`
. Configurez le référentiel MySQL : `yum install mysql80-community-release-el7-3.noarch.rpm`

